name: Maven Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload geoshell.zip
        uses: actions/upload-artifact@v2
        with:
          name: geoshell.zip
          path: target/geo-shell-*-app.zip
      - name: Upload geoshell.jar
        uses: actions/upload-artifact@v2
        with:
          name: geoshell.jar
          path: target/geo-shell-app-*.jar
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/generated-docs
          CLEAN: false